# Name of the project
PROJECT_NAME = RTMS

# Output directory
BUILD = build

# All source code files
SRC = project_main.c\
src/rtms_functions.c

# Project Output name
PROJECT_OUTPUT = $(BUILD)/$(PROJECT_NAME).exe

# Default target built
$(PROJECT_NAME):all

# Run the target even if the matching name exists
.PHONY: run clean test doc all

all: $(SRC) $(BUILD)
	gcc $(SRC) $(INC) -o $(PROJECT_OUTPUT).exe

# Call `make run` to run the application
run:$(PROJECT_NAME)
	./$(PROJECT_OUTPUT).exe


# Remove all the built files, invoke by `make clean`
clean:
	rm -rf $(BUILD) $(DOCUMENTATION_OUTPUT) *.gcda *.gcno *.gcov

# Create new build folder if not present
$(BUILD):
	mkdir build